services:
  - type: web
    name: tumbados-gaming-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
        optional: true
    healthCheckPath: /
    autoDeploy: true 